graph TB;
    A((Living Thing))-->B((Plant))
    A-->C((Animal));
    B-->E((Herbaceous))
    B-->F((Woody))
    C-->H((Fish))
    C-->I((Lizard))
    C-->J((Bird))
    C-->K((Mammal))


  style A fill:#FFFFFF, stroke:#FFFFFF;
  style B fill:#FFFFFF, stroke:#FFFFFF;
  style C fill:#FFFFFF, stroke:#FFFFFF;

  style E fill:#FFFFFF, stroke:#FFFFFF;
  style F fill:#FFFFFF, stroke:#FFFFFF;

  style H fill:#FFFFFF, stroke:#FFFFFF;
  style I fill:#FFFFFF, stroke:#FFFFFF;
  style J fill:#FFFFFF, stroke:#FFFFFF;
  style K fill:#FFFFFF, stroke:#FFFFFF;
