%%{init: {"theme": "neutral", "logLevel": 1 }}%%

graph LR
    FIRST["&quot;this &quot;"]--->A{<br><font face=courier size=4 color=white>concat<br>&nbsp}
    SECOND["&quot;is a &quot;"]--->A
    A ---> Output1["&quot;this is a &quot;"]
    Output1 ---> B{<br><font face=courier size=4 color=white>concat<br>&nbsp}
    THIRD["&quot;tedious &quot;"] ---> B
    B ---> Output2["&quot;this is a tedious &quot;"]

    example["&quot;example of &quot;"] --> C{<br><font face=courier size=4 color=white>concat<br>&nbsp}
    chaining["&quot;chaining&quot;"] --> C

    C ---> Output3["&quot;example of chaining&quot;"]

    Output2 ---> D{<br><font face=courier size=4 color=white>concat<br>&nbsp}
    Output3 ---> D

    D ---> Output4["&quot;this is a tedious example of chaining"]

    style A fill:#4E2A84

    style B fill:#4E2A84
    style C fill:#4E2A84
    style D fill:#4E2A84
