%%{init: {"theme": "neutral", "logLevel": 1 }}%%

graph LR
    FIRST["&quot;this is&quot;"]--->|"string"|A{<br><font face=courier size=4 color=white>concat<br>&nbsp}
    SECOND["&quot;a test&quot;"]--->|"string" |A
    A ---> Output["&quot;this is a test&quot;"]

    style A fill:#4E2A84
