%%{init: {"theme": "neutral", "logLevel": 1 }}%%

graph LR
    FIRST["&quot;woof woof&quot;"]--->|string|A{<br><font face=courier size=4 color=white>prefix<br>&nbsp}
    SECOND[4]--->|number|A
    A ---> Output["&quot;woof&quot;"]

    style A fill:#4E2A84
