%%{init: {"theme": "neutral", "logLevel": 1 }}%%

graph LR
    FIRST["&quot;woof woof&quot;"]--->A{<br><font face=courier size=4 color=white>length<br>&nbsp}
    A ---> Output1[9]
    Output1 ---> B{<br><font face=courier size=4 color=white>-<br>&nbsp}
    SECOND[4]--->B
    B ---> Output2[5]



    Output2 --> C{<br><font face=courier size=4 color=white>prefix<br>&nbsp}
    FIRST ---> C

    C ---> Output3[?]

    style A fill:#4E2A84
    style B fill:#4E2A84
    style C fill:#4E2A84
