%%{init: {"theme": "neutral", "logLevel": 1 }}%%

graph LR
    FIRST[50]--->|width|A{<br><font face=courier size=4 color=white>rectangle<br>&nbsp}
    SECOND[50]--->|height|A
    THIRD['solid']--->|mode|A
    FOURTH['blue']--->|color|A
    A ---> Output[ &nbsp &nbsp &nbsp]

    style A fill:#4E2A84
    style Output fill:#0000FF
